Sitegeist:
  Bitzer:
    factories:
      'Sitegeist\Bitzer\Translation\Domain\Task\Translation\TranslationTask': 'Sitegeist\Bitzer\Translation\Domain\Task\Translation\TranslationTaskFactory'
    Translation:
      languageDimension: 'language'
      assignments: {}
#       en:
#         de:
#           agents: ['Acme.Site:GermanTranslator']
#           interval: 'P1D'
